### ISSUE TITLE
怎么提交作业？

### ISSUE THREAD

**Issue by StarashZero** [sysu-swi/homework#1]
请问怎么提交作业

**Comment by youngdou** [comment]
https://sysu-swi.github.io/homework-start#33-%E7%BC%96%E8%BE%91%E5%B9%B6%E6%8F%90%E4%BA%A4%E7%AC%AC%E4%B8%80%E6%AC%A1%E4%BD%9C%E4%B8%9A

**Comment by StarashZero** [comment]
是只要上传到自己的仓库里就行了吗，那TA们怎么知道是我的作业呢
